spring:
  rabbitmq:
    host: 192.168.12.168
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true

    # publisher-confirm-type: 取值有三个：
    #（1）默认值为none，禁用发布确认模式
    #（2）correlated是发布消息成功到交换器后会触发回调方法
    #（3）simple有两种效果：
    # 其一是和 correlated一样消息发布成功后会触发回调方法；
    # 其二是在发布消息成功后使用rabbitTemplate调用waitForConfirms或waitForConfirmsOrDie方法等待broker节点返回发送结果，
    # 根据返回结果来判定下一步的逻辑，要注意的点是waitForConfirmsOrDie方法如果返回false则会关闭channel，则接下来无法发送消息到broker;

    listener:
      simple:
        acknowledge-mode: manual

