spring:
  main:
    # 告诉spring可能会出现循环依赖，spring自行解决
    allow-circular-references: true
  # 数据源
  datasource:
    # 数据源连接配置
    url: jdbc:mysql://127.0.0.1:3306/ecommerce_data?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: ImoocEngineeringTechnologyHikariCP


conditional:
  rand:
    type: int

# 配置自动装配 okhttp starter
custom:
  okhttp: auto