spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/interview?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #mybatis一级缓存范围，默认是开启session
    local-cache-scope: session
    # 开启二级缓存,且在mapper中<cache/> ，默认未开启 false,一般不开启容易产生脏读
    cache-enabled: true
    #打印sql语句的日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  #打印com.study.mybatis.dao包下的debug日志
#  logging:
#    level: com.study.mybatis.dao

